baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Kingsley blog'
theme = "Papermod"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  author = "kingsley"
  [params.homeInfoParams]
    Title = "Hi, make huge 👋" 
    Content = "..."
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/Kuangdd01"
  [[params.socialIcons]]
    name = "googlescholar"
    url = "https://scholar.google.com/citations?user=JQ5cm3UAAAAJ&hl=en"
