baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Kingsley's blog'
theme = "Papermod"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  # params 下的配置保留，用于页面显示
  author = "kingsley"

  # --- 添加这一块来实现 Banner ---
  [params.homeInfoParams]
    Title = "Hi, make huge 👋"     # Banner 的大标题
    Content = "这里是我的博客简介，可以在这里写一段自我介绍或者网站说明。" # Banner 的正文内容
  
  # 如果你想在 Banner 右侧显示社交图标（GitHub, Twitter等）
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/Kuangdd01"
  [[params.socialIcons]]
    name = "googlescholar"
    url = "https://scholar.google.com/citations?user=JQ5cm3UAAAAJ&hl=en"
